esphome:
  project:
    name: "SiliconAvatar.MiniR2_Package"
    version: "SiliconAvatar-2023.2.19"
  min_version: "2023.2.0"

esp8266:
  restore_from_flash: true
  board: esp01_1m

# Enable logging
logger:

time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    id: relay_1
    pin: GPIO12

light:
  - platform: binary
    id: light_1
    name: Light
    output: relay_1    

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle: 
          id: light_1


# This GPIO is the S1/S2 switch contact.
# Toggle the output relay on every state change of this input (IE Off->On & On->Off)
  - platform: gpio
    pin: GPIO04
    id: switch_1
    name: Toggle Switch Status
    on_press:
      then:
        - light.toggle: 
            id: light_1
    on_release:
      then:
        - light.toggle: 
            id: light_1