i2c:

sensor:
  - platform: bmp280_i2c
    # temperature:
    #   name: Temperature
    #   oversampling: 16x
    #   filters:
    #   - lambda: return x * (9.0/5.0) + 32.0;
    #   update_interval: 1s
    pressure:
      name: Pressure
      oversampling: 16x
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
          send_first_at: 3
    address: 0x76
    update_interval: 1s