esphome:
  project:
    name: "SiliconAvatar.S31_AlwaysOn_Package"
    version: "SiliconAvatar-2023.2.15"
  min_version: "2023.2.0"
  on_boot:
    - priority: 600
      then:
        - switch.turn_on: relay
    - priority: -100
      then:
      - if:
          condition:
            lambda: 'return ( (id(select_led).state == "Normal On") );'
          then:
            light.turn_on: blue_led

esp8266:
  restore_from_flash: true
  board: esp01_1m

uart:
  rx_pin: RX
  baud_rate: 4800

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

binary_sensor:
  # Template binary sensor to display if device is in-use or not
  - platform: template
    id: in_use
    name: Device In Use

light:
  - platform: status_led
    id: blue_led
    pin:
      number: GPIO13
      inverted: true

switch:
  # relay output
  - platform: gpio
    id: relay
    pin: GPIO12
    entity_category: ''
    restore_mode: ALWAYS_ON
    on_turn_off:
      - switch.turn_on: relay

# clock input from Home Assistant used to calculate total daily energy
time:
  - platform: homeassistant
    id: homeassistant_time

select:
    # option to disable blue LED
  - platform: template
    name: Status LED Config
    id: select_led
    optimistic: true
    entity_category: config
    options:
      - Normal On
      - Normal Off
    initial_option: Normal On
    restore_value: true
    icon: mdi:led-on
    on_value:
      then:
      - if:
          condition:
            lambda: 'return ( (id(select_led).state == "Normal On") );'
          then:
            light.turn_on: blue_led
      - if:
          condition:
            lambda: 'return ( (id(select_led).state == "Normal Off") );'
          then:
            light.turn_off: blue_led